#server
server:
  port: 8888
spring:
  application:
    name: mszlu_blog

  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 520
  redis:
    host: 120.25.253.42
    port: 6379
    password: 123520
      # 连接池最大连接数（使用负值表示没有限制）
      #spring.redis.jedis.pool.max-active=8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      # spring.redis.jedis.pool.max-wait=-1
      # 连接池中的最大空闲连接
      #spring.redis.jedis.pool.max-idle=8
      # 连接池中的最小空闲连接
      #spring.redis.jedis.pool.min-idle=0
    # 连接超时时间（毫秒）
    #spring.redis.timeout=5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000

  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 20MB
      # 单个文件的最大值
      max-file-size: 2MB


#mybatis-plus
mybatis-plus:
  configuration:
    #日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis的驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    #设置表名的前缀为ms_,之后只需要表名后面的名字匹配上就好了
    db-config:
      table-prefix: ms_


